FROM tensorflow/tensorflow:devel-py3
# FROM hub.oneflow.com/library/ts-jupyter-py3:v3

# RUN apt-get update -y \
#     && pip install tensorboard -i https://pypi.tuna.tsinghua.edu.cn/simple

# VOLUME /logs

# EXPOSE 6006
# CMD ["/bin/bash"]